### ISSUE TITLE
add gplinks support

### ISSUE THREAD

**Issue by askfriends** [BloodyToolzz/Bloody-Bypasser#1]

**Comment by BloodyToolzz** [comment]
I may not be able to add it because this bypasser uses the bypass.vip API which doesn't support this link.

I might research on gplinks and see if there is any bypasser to implement into the code.

But all that after I get my PC back as I'm very busy with school life and I'm not able to use my PC.

**Comment by askfriends** [comment]
> I may not be able to add it because this bypasser uses the bypass.vip API which doesn't support this link.
> 
> I might research on gplinks and see if there is any bypasser to implement into the code.
> 
> But all that after I get my PC back as I'm very busy with school life and I'm not able to use my PC.

best of luck bro

**Comment by BloodyToolzz** [comment]
@askfriends GPLinks Support has been added!
Check out the commit [here](https://github.com/BloodyToolzz/Bloody-Bypasser/commit/64fb7281d4eaeb7b846509db00648ce22ef5eed2)

Also I don't take credits for the bypasser, it belongs to xcscxr
I just implemented it into my code

**Comment by askfriends** [comment]
> @askfriends GPLinks Support has been added! Check out the commit [here](https://github.com/BloodyToolzz/Bloody-Bypasser/commit/64fb7281d4eaeb7b846509db00648ce22ef5eed2)
> 
> Also I don't take credits for the bypasser, it belongs to xcscxr I just implemented it into my code

Thanks a lot man!!!!
it really works now. thanks a bunch.
btw can i request more sites in future?

**Comment by BloodyToolzz** [comment]
> > @askfriends GPLinks Support has been added! Check out the commit [here](https://github.com/BloodyToolzz/Bloody-Bypasser/commit/64fb7281d4eaeb7b846509db00648ce22ef5eed2)
> > 
> > Also I don't take credits for the bypasser, it belongs to xcscxr I just implemented it into my code
> 
> Thanks a lot man!!!!
> it really works now. thanks a bunch.
> btw can i request more sites in future?

No problem!

Feel free to request more sites, the more sites, the better the tool becomes 👍
